// Generated by scripts/el-timing.py — ElevenLabs two-voice timelines.
export const EL_TL_DELTA = {
  s01: { from: 0, dur: 225 },
  s02: { from: 225, dur: 266 },
  s03: { from: 491, dur: 309 },
  s04: { from: 800, dur: 263 },
  s05: { from: 1063, dur: 318 },
  s06: { from: 1381, dur: 438 },
  s07: { from: 1819, dur: 398 },
  s08: { from: 2217, dur: 338 },
  s09: { from: 2555, dur: 191 },
} as const;
export const EL_TL_DELTA_TOTAL = 2746;

export const EL_TL_EPSILON = {
  s01: { from: 0, dur: 290 },
  s02: { from: 290, dur: 470 },
  s03: { from: 760, dur: 522 },
  s04: { from: 1282, dur: 326 },
  s05: { from: 1608, dur: 402 },
  s06: { from: 2010, dur: 388 },
  s07: { from: 2398, dur: 335 },
  s08: { from: 2733, dur: 402 },
  s09: { from: 3135, dur: 503 },
  s10: { from: 3638, dur: 218 },
} as const;
export const EL_TL_EPSILON_TOTAL = 3856;

export const EL_TL_ZETA = {
  s01: { from: 0, dur: 218 },
  s02: { from: 218, dur: 266 },
  s03: { from: 484, dur: 474 },
  s04: { from: 958, dur: 388 },
  s05: { from: 1346, dur: 285 },
  s06: { from: 1631, dur: 230 },
  s07: { from: 1861, dur: 316 },
  s08: { from: 2177, dur: 242 },
  s09: { from: 2419, dur: 294 },
  s10: { from: 2713, dur: 251 },
} as const;
export const EL_TL_ZETA_TOTAL = 2964;

export const EL_TL_ETA = {
  s01: { from: 0, dur: 146 },
  s02: { from: 146, dur: 390 },
  s03: { from: 536, dur: 419 },
  s04: { from: 955, dur: 179 },
  s05: { from: 1134, dur: 270 },
  s06: { from: 1404, dur: 318 },
  s07: { from: 1722, dur: 342 },
  s08: { from: 2064, dur: 251 },
  s09: { from: 2315, dur: 198 },
} as const;
export const EL_TL_ETA_TOTAL = 2513;

export const EL_TL_THETA = {
  s01: { from: 0, dur: 246 },
  s02: { from: 246, dur: 460 },
  s03: { from: 706, dur: 256 },
  s04: { from: 962, dur: 453 },
  s05: { from: 1415, dur: 210 },
  s06: { from: 1625, dur: 290 },
  s07: { from: 1915, dur: 328 },
  s08: { from: 2243, dur: 261 },
  s09: { from: 2504, dur: 201 },
} as const;
export const EL_TL_THETA_TOTAL = 2705;
